/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cave.gltf 
Author: David Glynch (https://sketchfab.com/yaveselyigolovastic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-cave-entrance-likes-a-head-4a7643ff40dd42c3bfafd73f2d84547c
Title: The cave entrance likes a  head
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/cave/cave.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.ivy_Trunk_0.geometry} material={materials.Trunk} />
          <mesh geometry={nodes.ivy_leaf_0.geometry} material={materials.leaf} />
          <mesh geometry={nodes.ivy_leaf_0_1.geometry} material={materials.leaf} />
        </group>
        <mesh geometry={nodes.cave_low_cave_0.geometry} material={materials.cave} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/cave/cave.gltf')
